-- IMPORTING DATASETS

CREATE TABLE PHARMACY_DATASET (DATE date,
                               YEAR	int,
							   MONTH int,
							   TOTAL_PHARMACIES	int,
							   TOTAL_PHARMACIES_EXCLUDING_DISTANCE_SELLERS int,
							   TOTAL_DISTANCE_SELLING_PHARMACIES int,
							   TOTAL_HUNDRED_HOUR_PHARMACIES int,
							   SMALL int,
							   MEDIUM int,
							   LARGE int,	
							   TOTAL_PHARMACIES_EXCLUDING_DISTANCE_SELLERS_OPENED int,
							   TOTAL_PHARMACIES_EXCLUDING_DISTANCE_SELLERS_CLOSED int,
							   PHARMACIES_EXCLUDING_DISTANCE_SELLERS_NET_CHANGE	int,
							   SMALL_PHARMACIES_OPENED int,
							   SMALL_PHARMACIES_CLOSED int,
							   SMALL_PHARMACIES_NET_CHANGE int,
							   MEDIUM_PHARMACIES_OPENED int,
							   MEDIUM_PHARMACIES_CLOSED	int,
							   MEDIUM_PHARMACIES_NET_CHANGE	int,
							   LARGE_PHARMACIES_OPENED int,
							   LARGE_PHARMACIES_CLOSED int,
							   LARGE_PHARMACIES_NET_CHANGE int,
							   DISTANCE_SELLERS_OPENED int,
							   DISTANCE_SELLERS_CLOSED int,
							   DISTANCE_SELLERS_NET_CHANGE int


);

SELECT * FROM PHARMACY_DATASET

-- 1. What are the monthly and yearly trends for pharmacy openings and closures?

-- Monthly trend

SELECT YEAR, MONTH, 
SUM (SMALL_PHARMACIES_OPENED + MEDIUM_PHARMACIES_OPENED + LARGE_PHARMACIES_OPENED) AS TOTAL_OPENED,
SUM (SMALL_PHARMACIES_CLOSED + MEDIUM_PHARMACIES_CLOSED + LARGE_PHARMACIES_CLOSED) AS TOTAL_CLOSED
FROM PHARMACY_DATASET
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

-- 2. Yearly trend

CREATE TABLE PHARAMCY_YEARLY_TREND AS (SELECT YEAR, 
SUM (SMALL_PHARMACIES_OPENED + MEDIUM_PHARMACIES_OPENED + LARGE_PHARMACIES_OPENED) AS TOTAL_OPENED,
SUM (SMALL_PHARMACIES_CLOSED + MEDIUM_PHARMACIES_CLOSED + LARGE_PHARMACIES_CLOSED) AS TOTAL_CLOSED,
SUM (SMALL_PHARMACIES_NET_CHANGE + MEDIUM_PHARMACIES_NET_CHANGE + LARGE_PHARMACIES_NET_CHANGE) AS TOTAL_NET_CHANGE
FROM PHARMACY_DATASET
GROUP BY YEAR
ORDER BY YEAR)

SELECT * FROM PHARAMCY_YEARLY_TREND

-- 2.  Are closures proportionate to pharmacy sizes?

CREATE TABLE PHARMACY_CLOSURE_BY_SIZE AS (SELECT 'SMALL' AS PHARMACY_SIZE,
SUM (SMALL_PHARMACIES_CLOSED) AS TOTAL_CLOSED
FROM PHARMACY_DATASET
UNION ALL
SELECT 'MEDIUM',
SUM (MEDIUM_PHARMACIES_CLOSED)
FROM PHARMACY_DATASET
UNION ALL
SELECT 'LARGE',
SUM (LARGE_PHARMACIES_CLOSED) 
FROM PHARMACY_DATASET)

SELECT * FROM PHARMACY_CLOSURE_BY_SIZE

-- 3. What are the implications for healthcare access?

-- Trend in total pharmacies

SELECT YEAR, 
MAX (TOTAL_PHARMACIES) AS ANNUAL_COUNT_OF_PHARMACIES
FROM PHARMACY_DATASET
GROUP BY YEAR
ORDER BY YEAR

-- Net change over time

SELECT YEAR,
SUM(SMALL_PHARMACIES_NET_CHANGE + MEDIUM_PHARMACIES_NET_CHANGE + LARGE_PHARMACIES_NET_CHANGE) AS ANNUAL_NET_CHANGE
FROM PHARMACY_DATASET
GROUP BY YEAR
ORDER BY YEAR

-- 4. Are distance sellers replacing physical pharmacies?
-- Distance sellers

CREATE TABLE DISTANCE_SELLERS_TREND AS (SELECT YEAR,
SUM (DISTANCE_SELLERS_OPENED) AS DISTANCE_OPENED,
SUM (DISTANCE_SELLERS_CLOSED) AS DISTANCE_CLOSED,
SUM (DISTANCE_SELLERS_NET_CHANGE) AS DISTANCE_NET_CHANGE
FROM PHARMACY_DATASET
GROUP BY YEAR
ORDER BY YEAR)

SELECT * FROM DISTANCE_SELLERS_TREND

-- Net change Physical

CREATE TABLE PHYSICAL_NET_CHANGE AS (SELECT YEAR,
SUM(SMALL_PHARMACIES_NET_CHANGE + MEDIUM_PHARMACIES_NET_CHANGE + LARGE_PHARMACIES_NET_CHANGE) AS PHYSICAL_NET_CHANGE
FROM PHARMACY_DATASET
GROUP BY YEAR
ORDER BY YEAR)

SELECT * FROM PHYSICAL_NET_CHANGE

-- Is growth in distance-selling pharmacies associated with decline in physical pharmacies?
SELECT YEAR,
SUM(distance_sellers_net_change) AS distance_growth,
SUM(pharmacies_excluding_distance_sellers_net_change) AS physical_change
FROM pharmacy_dataset
GROUP BY year
ORDER BY year

-- 5. Which pharmacy size contributes most to the industry's net growth?

SELECT 
SUM(small_pharmacies_net_change) AS small_growth,
SUM(medium_pharmacies_net_change) AS medium_growth,
SUM(large_pharmacies_net_change) AS large_growth
FROM pharmacy_dataset

-- KPIs For Summary Cards

-- Total Online Pharmacies

SELECT SUM(TOTAL_DISTANCE_SELLING_PHARMACIES) AS TOTAL_ONLINE_PHARMACY FROM PHARMACY_DATASET

-- Total Physical Pharmacies

SELECT SUM(TOTAL_PHARMACIES_EXCLUDING_DISTANCE_SELLERS) AS TOTAL_PHYSICAL_PHARMACY FROM PHARMACY_DATASET

-- Total Distance Net Change

SELECT SUM(DISTANCE_NET_CHANGE) AS TOTAL_DISTANCE_NET_CHANGE FROM DISTANCE_SELLERS_TREND

-- Total Physical Net Change

SELECT SUM(PHARMACIES_EXCLUDING_DISTANCE_SELLERS_NET_CHANGE) AS TOTAL_PHYSICAL_NET_CHANGE FROM PHARMACY_DATASET



